{"uuid":"ec72419d-b0ee-4203-8491-cd38b99408d1","historyId":"b3c95db8ac38b27bad1b5bdb3e37998f","fullName":"com.thetestingacademy.ex03_Selenium_Locators.TestSelenium19_Mini_Project2.vwo_free_trail_error_verify","labels":[{"name":"package","value":"com.thetestingacademy.ex03_Selenium_Locators.TestSelenium19_Mini_Project2"},{"name":"testClass","value":"com.thetestingacademy.ex03_Selenium_Locators.TestSelenium19_Mini_Project2"},{"name":"testMethod","value":"vwo_free_trail_error_verify"},{"name":"parentSuite","value":"All Test Suite"},{"name":"suite","value":"LearningSeleniumATB10x"},{"name":"subSuite","value":"com.thetestingacademy.ex03_Selenium_Locators.TestSelenium19_Mini_Project2"},{"name":"host","value":"promodes-MacBook-Pro.local"},{"name":"thread","value":"74205@promodes-MacBook-Pro.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"owner","value":"Pramod"},{"name":"severity","value":"blocker"}],"links":[{"name":"https://bugz.atlassian.net/browse/BUG-17","type":"tms"}],"name":"vwo_free_trail_error_verify","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [The email address you entered is incorrect.] but found []","trace":"java.lang.AssertionError: expected [The email address you entered is incorrect.] but found []\n\tat org.testng.Assert.fail(Assert.java:111)\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\n\tat org.testng.Assert.assertEquals(Assert.java:132)\n\tat org.testng.Assert.assertEquals(Assert.java:656)\n\tat org.testng.Assert.assertEquals(Assert.java:666)\n\tat com.thetestingacademy.ex03_Selenium_Locators.TestSelenium19_Mini_Project2.vwo_free_trail_error_verify(TestSelenium19_Mini_Project2.java:52)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\n\tat org.testng.TestRunner.run(TestRunner.java:614)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\n\tat org.testng.TestNG.run(TestNG.java:1079)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\n"},"stage":"finished","description":"Verify that the error message comes with invalid email on signup page.","steps":[],"attachments":[],"parameters":[],"start":1743221193231,"stop":1743221200110}